version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: pabuyan_postgres_v6
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: pabuyan_db
    ports:
      - "5432:5432"
